/// <reference types="next" />
/// <reference types="next/types/global" />
/// <reference types="next/image-types/global" />

// NOTE:
// This file is automatically generated by Next.js.
// Do NOT edit this file — if you need to add custom type declarations,
// create a separate `*.d.ts` file in the project root instead.
